### ISSUE TITLE
 No Objects in samsung.0 created - 2

### ISSUE THREAD

**Issue by OneCreek** [iobroker-community-adapters/ioBroker.samsung#138] opened 2023-03-22 10:22 UTC
Still #117 exists for me... But I could not reopen. Hope this new updated report is ok.

**Describe the bug**  
No objects are in the objects branch. No use possible. 

**To Reproduce**  
SamsungHJ with model 2015: UE55ju6850
1. install Adapter
2. create instance
3. connect via IP
4. save
5. enter PIN shown on TV in instance
6. save

**Expected behavior**  
I expect to have objects in the object branch to use the adapter

**Screenshots & Logfiles**  
[iobroker add samsung auto --host.txt](https://github.com/iobroker-community-adapters/ioBroker.samsung/files/11038875/iobroker.add.samsung.auto.--host.txt)
[samsung.0 2023-03-22 110925.823 log.txt](https://github.com/iobroker-community-adapters/ioBroker.samsung/files/11038876/samsung.0.2023-03-22.110925.823.log.txt)

**Versions:**  
 - Adapter version: v0.5.11
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: docker

Instance shows connected:
![grafik](https://user-images.githubusercontent.com/107502675/226871894-d3b86365-b67d-44ae-bd1e-ef7e49157a6d.png)

but no objects exist:
![grafik](https://user-images.githubusercontent.com/107502675/226872063-c048aeb0-6225-4a1d-a0e5-63dac81719c4.png)

**Comment by onki2** [comment] 2023-07-23 16:37
Hi, 
i see exactly the same issue. Last log entery is  "Connection to TV initialised", and no objects are created. 
Best regards, 
Stefan

**Comment by OneCreek** [comment] 2023-09-01 10:56
@onki2 unfortunately the situation is still the same for me since 1 year... apparently we are abandoned :(

**Comment by Apollon77** [comment] 2023-09-02 14:22
> apparently

hm ... not really ... but the problem is that none of the developers that are available seems to have such TVs :-(

So the will is there, but not the material

**Comment by mcm1957** [comment] 2024-09-28 19:57
fixed with upcoming 0.6.1

**Closed** 2024-09-28 19:57 UTC
Labels: bug, fixed
